#!/usr/bin/env node
/**
 * Wire cursor-hud into ~/.cursor/cli-config.json statusLine (merge, don't wipe).
 * Backs up cli-config.json and the previous statusline.sh first.
 */
import {
  copyFileSync,
  existsSync,
  mkdirSync,
  readFileSync,
  writeFileSync,
  chmodSync,
} from "node:fs";
import { homedir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
const DIST = join(ROOT, "dist", "index.js");
const CURSOR_DIR = join(homedir(), ".cursor");
const CLI_CONFIG = join(CURSOR_DIR, "cli-config.json");
const WRAPPER = join(CURSOR_DIR, "cursor-hud.sh");
const HUD_DIR = join(CURSOR_DIR, "cursor-hud");

function die(msg) {
  console.error(msg);
  process.exit(1);
}

if (!existsSync(DIST)) {
  die(`Missing ${DIST}. Run: npm run build`);
}

mkdirSync(HUD_DIR, { recursive: true, mode: 0o700 });
mkdirSync(join(HUD_DIR, "capture"), { recursive: true, mode: 0o700 });

const stamp = new Date().toISOString().replace(/[:.]/g, "-");

if (existsSync(CLI_CONFIG)) {
  copyFileSync(CLI_CONFIG, join(HUD_DIR, `cli-config.backup-${stamp}.json`));
}

const oldStatusline = join(CURSOR_DIR, "statusline.sh");
if (existsSync(oldStatusline)) {
  copyFileSync(oldStatusline, join(HUD_DIR, `statusline.sh.backup-${stamp}`));
}

const wrapper = `#!/usr/bin/env bash
# cursor-hud statusLine wrapper — generated by scripts/setup.mjs
set -euo pipefail
NODE="\${CURSOR_HUD_NODE:-$(command -v node)}"
exec "$NODE" ${JSON.stringify(DIST)}
`;
writeFileSync(WRAPPER, wrapper, { mode: 0o755 });
chmodSync(WRAPPER, 0o755);

let config = {};
if (existsSync(CLI_CONFIG)) {
  try {
    config = JSON.parse(readFileSync(CLI_CONFIG, "utf8"));
  } catch (err) {
    die(`Failed to parse ${CLI_CONFIG}: ${err}`);
  }
}

config.statusLine = {
  type: "command",
  command: "~/.cursor/cursor-hud.sh",
  padding: 0,
  updateIntervalMs: 500,
  timeoutMs: 2000,
};

writeFileSync(CLI_CONFIG, JSON.stringify(config, null, 2) + "\n", "utf8");

console.log("cursor-hud setup complete.");
console.log(`  wrapper: ${WRAPPER}`);
console.log(`  cli-config: ${CLI_CONFIG}`);
console.log(`  capture: ${join(HUD_DIR, "capture")}`);
console.log("");
console.log("Next: start a new Cursor CLI session (`agent`).");
console.log("After one message, inspect:");
console.log(`  ${join(HUD_DIR, "capture", "latest-meta.json")}`);
