#!/usr/bin/env node
/**
 * Install cursor-hud production hooks into ~/.cursor/hooks.json (merge, idempotent).
 * P3 option A: preToolUse(Task) → agent-hooks.json running marks.
 */
import {
  copyFileSync,
  chmodSync,
  existsSync,
  mkdirSync,
  readFileSync,
  writeFileSync,
} from "node:fs";
import { homedir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
const AGENT_SRC = join(ROOT, "scripts", "hooks-agent.mjs");
const CURSOR_DIR = join(homedir(), ".cursor");
const HOOKS_DIR = join(CURSOR_DIR, "hooks");
const HOOKS_JSON = join(CURSOR_DIR, "hooks.json");
const WRAPPER = join(HOOKS_DIR, "cursor-hud-agent.sh");
const HUD_DIR = join(CURSOR_DIR, "cursor-hud");
const MARKERS = ["cursor-hud-agent.sh", "cursor-hud-capture.sh"];

const EVENTS = [
  { name: "preToolUse", args: "preToolUse", matcher: "Task" },
  { name: "postToolUse", args: "postToolUse", matcher: "Task" },
  { name: "subagentStart", args: "subagentStart" },
  { name: "subagentStop", args: "subagentStop" },
];

function die(msg) {
  console.error(msg);
  process.exit(1);
}

if (!existsSync(AGENT_SRC)) die(`Missing ${AGENT_SRC}`);

mkdirSync(HOOKS_DIR, { recursive: true, mode: 0o700 });
mkdirSync(HUD_DIR, { recursive: true, mode: 0o700 });

const stamp = new Date().toISOString().replace(/[:.]/g, "-");
if (existsSync(HOOKS_JSON)) {
  copyFileSync(HOOKS_JSON, join(HUD_DIR, `hooks.json.backup-${stamp}.json`));
}

const wrapper = `#!/usr/bin/env bash
# cursor-hud P3 agent hooks — generated by scripts/setup-hooks.mjs
set -euo pipefail
NODE="\${CURSOR_HUD_NODE:-$(command -v node)}"
EVENT="\${1:-unknown}"
exec "$NODE" ${JSON.stringify(AGENT_SRC)} "$EVENT"
`;
writeFileSync(WRAPPER, wrapper, { mode: 0o755 });
chmodSync(WRAPPER, 0o755);

let config = { version: 1, hooks: {} };
if (existsSync(HOOKS_JSON)) {
  try {
    const parsed = JSON.parse(readFileSync(HOOKS_JSON, "utf8"));
    if (parsed && typeof parsed === "object") config = parsed;
  } catch (err) {
    die(`Failed to parse ${HOOKS_JSON}: ${err}`);
  }
}
if (!config.version) config.version = 1;
if (!config.hooks || typeof config.hooks !== "object") config.hooks = {};

function isOurs(entry) {
  const cmd = String(entry?.command ?? "");
  return MARKERS.some((m) => cmd.includes(m));
}

for (const [name, list] of Object.entries(config.hooks)) {
  if (!Array.isArray(list)) continue;
  const kept = list.filter((e) => !isOurs(e));
  if (kept.length === 0) delete config.hooks[name];
  else config.hooks[name] = kept;
}

for (const ev of EVENTS) {
  const list = Array.isArray(config.hooks[ev.name]) ? config.hooks[ev.name] : [];
  const entry = { command: `./hooks/cursor-hud-agent.sh ${ev.args}` };
  if (ev.matcher) entry.matcher = ev.matcher;
  list.push(entry);
  config.hooks[ev.name] = list;
}

writeFileSync(HOOKS_JSON, JSON.stringify(config, null, 2) + "\n", { mode: 0o600 });

console.log("cursor-hud hooks installed (P3 option A).");
console.log(`  wrapper: ${WRAPPER}`);
console.log(`  hooks.json: ${HOOKS_JSON}`);
console.log(`  store: ${join(HUD_DIR, "agent-hooks.json")}`);
console.log("");
console.log("Disable: CURSOR_HUD_HOOKS=0");
console.log("Also capture payloads: CURSOR_HUD_HOOKS_CAPTURE=1");
console.log("Uninstall: npm run uninstall:hooks");
